import {
  ANNOUNCEMENT_TARGET_AUDIENCES,
  ANNOUNCEMENT_TYPES,
  BILLING_CYCLES,
  CHANGELOG_TYPES,
  ERROR_LOG_SEVERITIES,
  EVENT_TRIGGERED_BY,
  FEATURE_TYPES,
  HEALTH_CHECK_STATUSES,
  HEALTH_CHECK_TYPES,
  INVOICE_STATUSES,
  MESSAGE_SENDER_TYPES,
  PAYMENT_METHOD_KINDS,
  PAYMENT_METHOD_TYPES,
  PAYMENT_PROVIDERS,
  PAYMENT_STATUSES,
  SUBSCRIPTION_EVENT_TYPES,
  SUBSCRIPTION_STATUSES,
  SUPPORT_TICKET_CATEGORIES,
  SUPPORT_TICKET_PRIORITIES,
  SUPPORT_TICKET_STATUSES,
  TENANT_STATUSES,
  USAGE_METRICS,
  USER_ROLES,
} from "@/lib/api/central/enums"
import {
  useActivities,
  useAnnouncements,
  useApiKeys,
  useChangelog,
  useDomains,
  useErrorLogs,
  useHealthChecks,
  useImpersonationTokens,
  useInvoiceItems,
  useInvoices,
  useMetrics,
  usePaymentMethods,
  usePayments,
  usePermissions,
  usePlanFeatures,
  usePlans,
  useRoles,
  useSubscriptionEvents,
  useSubscriptionItems,
  useSubscriptions,
  useSupportMessages,
  useSupportTickets,
  useTenantConfigs,
  useTenants,
  useUsageRecords,
  useUsers,
} from "@/lib/api/central/hooks"
import {
  activityColumns,
  announcementColumns,
  apiKeyColumns,
  changelogColumns,
  domainColumns,
  errorLogColumns,
  healthCheckColumns,
  impersonationTokenColumns,
  invoiceColumns,
  invoiceItemColumns,
  metricColumns,
  paymentColumns,
  paymentMethodColumns,
  permissionColumns,
  planColumns,
  planFeatureColumns,
  roleColumns,
  subscriptionColumns,
  subscriptionEventColumns,
  subscriptionItemColumns,
  supportMessageColumns,
  supportTicketColumns,
  tenantColumns,
  tenantConfigColumns,
  usageRecordColumns,
  userColumns,
} from "@/lib/columns"
import { createResourcePage } from "@/lib/create-resource-page"
import {
  activitySchema,
  announcementSchema,
  apiKeySchema,
  changelogSchema,
  domainSchema,
  errorLogSchema,
  healthCheckSchema,
  impersonationTokenSchema,
  invoiceItemSchema,
  invoiceSchema,
  metricSchema,
  paymentMethodSchema,
  paymentSchema,
  permissionSchema,
  planFeatureSchema,
  planSchema,
  roleSchema,
  subscriptionEventSchema,
  subscriptionItemSchema,
  subscriptionSchema,
  supportMessageSchema,
  supportTicketSchema,
  tenantConfigSchema,
  tenantSchema,
  usageRecordSchema,
  userSchema,
} from "@/lib/schemas"

export const TenantsPage = createResourcePage({
  title: "Tenants",
  description: "Manage platform tenants and their lifecycle.",
  hooks: useTenants,
  columns: tenantColumns,
  schema: tenantSchema,
  fields: [
    { name: "name", label: "Name", type: "text" },
    { name: "slug", label: "Slug", type: "text" },
    { name: "domain", label: "Domain", type: "text" },
    { name: "status", label: "Status", type: "enum", values: TENANT_STATUSES },
    { name: "billing_cycle", label: "Billing cycle", type: "enum", values: BILLING_CYCLES },
    { name: "plan_id", label: "Plan ID", type: "text" },
    { name: "owner_name", label: "Owner name", type: "text" },
    { name: "owner_email", label: "Owner email", type: "email" },
  ],
  defaults: {
    name: "",
    slug: "",
    domain: "",
    status: "pending",
    billing_cycle: "monthly",
    plan_id: "",
    owner_name: "",
    owner_email: "",
  },
})

export const UsersPage = createResourcePage({
  title: "Users",
  description: "Central platform administrators and staff.",
  hooks: useUsers,
  columns: userColumns,
  schema: userSchema,
  fields: [
    { name: "name", label: "Name", type: "text" },
    { name: "email", label: "Email", type: "email" },
    { name: "password", label: "Password", type: "password" },
    { name: "role", label: "Role", type: "enum", values: USER_ROLES },
    { name: "is_active", label: "Active", type: "boolean" },
  ],
  defaults: {
    name: "",
    email: "",
    password: "",
    role: "support",
    is_active: true,
  },
})

export const PlansPage = createResourcePage({
  title: "Plans",
  description: "Subscription plans and pricing tiers.",
  hooks: usePlans,
  columns: planColumns,
  schema: planSchema,
  fields: [
    { name: "name", label: "Name", type: "text" },
    { name: "slug", label: "Slug", type: "text" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "tier", label: "Tier", type: "number" },
    { name: "price_monthly", label: "Monthly price (cents)", type: "number" },
    { name: "price_yearly", label: "Yearly price (cents)", type: "number" },
    { name: "currency", label: "Currency", type: "text" },
    { name: "trial_days", label: "Trial days", type: "number" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "is_active", label: "Active", type: "boolean" },
    { name: "is_public", label: "Public", type: "boolean" },
  ],
  defaults: {
    name: "",
    slug: "",
    description: "",
    tier: 1,
    price_monthly: 0,
    price_yearly: 0,
    currency: "USD",
    trial_days: 14,
    sort_order: 0,
    is_active: true,
    is_public: true,
  },
})

export const DomainsPage = createResourcePage({
  title: "Domains",
  hooks: useDomains,
  columns: domainColumns,
  schema: domainSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "domain", label: "Domain", type: "text" },
    { name: "is_primary", label: "Primary", type: "boolean" },
    { name: "is_fallback", label: "Fallback", type: "boolean" },
    { name: "verified", label: "Verified", type: "boolean" },
  ],
  defaults: {
    tenant_id: "",
    domain: "",
    is_primary: false,
    is_fallback: false,
    verified: false,
  },
})

export const SubscriptionsPage = createResourcePage({
  title: "Subscriptions",
  hooks: useSubscriptions,
  columns: subscriptionColumns,
  schema: subscriptionSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "plan_id", label: "Plan ID", type: "text" },
    { name: "status", label: "Status", type: "enum", values: SUBSCRIPTION_STATUSES },
    { name: "billing_cycle", label: "Billing cycle", type: "enum", values: BILLING_CYCLES },
    { name: "current_period_start", label: "Period start", type: "datetime-local" },
    { name: "current_period_end", label: "Period end", type: "datetime-local" },
    { name: "trial_ends_at", label: "Trial ends", type: "datetime-local" },
    { name: "payment_provider", label: "Provider", type: "enum", values: PAYMENT_PROVIDERS },
  ],
  defaults: {
    tenant_id: "",
    plan_id: "",
    status: "trialing",
    billing_cycle: "monthly",
    current_period_start: "",
    current_period_end: "",
    trial_ends_at: "",
    payment_provider: "stripe",
  },
})

export const InvoicesPage = createResourcePage({
  title: "Invoices",
  hooks: useInvoices,
  columns: invoiceColumns,
  schema: invoiceSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "subscription_id", label: "Subscription ID", type: "text" },
    { name: "invoice_number", label: "Invoice number", type: "text" },
    { name: "status", label: "Status", type: "enum", values: INVOICE_STATUSES },
    { name: "amount_due", label: "Amount due (cents)", type: "number" },
    { name: "amount_paid", label: "Amount paid (cents)", type: "number" },
    { name: "currency", label: "Currency", type: "text" },
    { name: "billing_period_start", label: "Period start", type: "date" },
    { name: "billing_period_end", label: "Period end", type: "date" },
    { name: "due_date", label: "Due date", type: "date" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  defaults: {
    tenant_id: "",
    subscription_id: "",
    invoice_number: "",
    status: "draft",
    amount_due: 0,
    amount_paid: 0,
    currency: "USD",
    billing_period_start: "",
    billing_period_end: "",
    due_date: "",
    notes: "",
  },
})

export const PaymentsPage = createResourcePage({
  title: "Payments",
  hooks: usePayments,
  columns: paymentColumns,
  schema: paymentSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "invoice_id", label: "Invoice ID", type: "text" },
    { name: "amount", label: "Amount (cents)", type: "number" },
    { name: "currency", label: "Currency", type: "text" },
    { name: "status", label: "Status", type: "enum", values: PAYMENT_STATUSES },
    { name: "payment_provider", label: "Provider", type: "enum", values: PAYMENT_PROVIDERS },
    { name: "provider_payment_id", label: "Provider payment ID", type: "text" },
    { name: "payment_method_type", label: "Method type", type: "enum", values: PAYMENT_METHOD_TYPES },
    { name: "payment_method_last4", label: "Last 4", type: "text" },
  ],
  defaults: {
    tenant_id: "",
    invoice_id: "",
    amount: 0,
    currency: "USD",
    status: "pending",
    payment_provider: "stripe",
    provider_payment_id: "",
    payment_method_type: "card",
    payment_method_last4: "",
  },
})

export const RolesPage = createResourcePage({
  title: "Roles",
  hooks: useRoles,
  columns: roleColumns,
  schema: roleSchema,
  fields: [
    { name: "name", label: "Name", type: "text" },
    { name: "guard_name", label: "Guard", type: "text" },
  ],
  defaults: { name: "", guard_name: "web" },
})

export const PermissionsPage = createResourcePage({
  title: "Permissions",
  hooks: usePermissions,
  columns: permissionColumns,
  schema: permissionSchema,
  fields: [
    { name: "name", label: "Name", type: "text" },
    { name: "guard_name", label: "Guard", type: "text" },
    { name: "module", label: "Module", type: "text" },
  ],
  defaults: { name: "", guard_name: "web", module: "" },
})

export const ApiKeysPage = createResourcePage({
  title: "API Keys",
  hooks: useApiKeys,
  columns: apiKeyColumns,
  schema: apiKeySchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "name", label: "Name", type: "text" },
    { name: "expires_at", label: "Expires at", type: "datetime-local" },
    { name: "is_active", label: "Active", type: "boolean" },
  ],
  defaults: { tenant_id: "", name: "", expires_at: "", is_active: true },
})

export const SupportTicketsPage = createResourcePage({
  title: "Support Tickets",
  hooks: useSupportTickets,
  columns: supportTicketColumns,
  schema: supportTicketSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "category", label: "Category", type: "enum", values: SUPPORT_TICKET_CATEGORIES },
    { name: "priority", label: "Priority", type: "enum", values: SUPPORT_TICKET_PRIORITIES },
    { name: "status", label: "Status", type: "enum", values: SUPPORT_TICKET_STATUSES },
    { name: "subject", label: "Subject", type: "text" },
    { name: "body", label: "Body", type: "textarea" },
    { name: "assigned_to", label: "Assigned to (user ID)", type: "number" },
  ],
  defaults: {
    tenant_id: "",
    category: "general",
    priority: "medium",
    status: "open",
    subject: "",
    body: "",
    assigned_to: null,
  },
})

export const ErrorLogsPage = createResourcePage({
  title: "Error Logs",
  hooks: useErrorLogs,
  columns: errorLogColumns,
  schema: errorLogSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "severity", label: "Severity", type: "enum", values: ERROR_LOG_SEVERITIES },
    { name: "channel", label: "Channel", type: "text" },
    { name: "message", label: "Message", type: "textarea" },
    { name: "occurred_at", label: "Occurred at", type: "datetime-local" },
  ],
  defaults: {
    tenant_id: "",
    severity: "error",
    channel: "app",
    message: "",
    occurred_at: "",
  },
})

export const ActivitiesPage = createResourcePage({
  title: "Activities",
  hooks: useActivities,
  columns: activityColumns,
  schema: activitySchema,
  fields: [
    { name: "log_name", label: "Log name", type: "text" },
    { name: "description", label: "Description", type: "text" },
    { name: "event", label: "Event", type: "text" },
  ],
  defaults: { log_name: "", description: "", event: "" },
})

export const AnnouncementsPage = createResourcePage({
  title: "Announcements",
  hooks: useAnnouncements,
  columns: announcementColumns,
  schema: announcementSchema,
  fields: [
    { name: "title", label: "Title", type: "text" },
    { name: "body", label: "Body", type: "textarea" },
    { name: "type", label: "Type", type: "enum", values: ANNOUNCEMENT_TYPES },
    {
      name: "target_audience",
      label: "Audience",
      type: "enum",
      values: ANNOUNCEMENT_TARGET_AUDIENCES,
    },
    { name: "starts_at", label: "Starts at", type: "datetime-local" },
    { name: "ends_at", label: "Ends at", type: "datetime-local" },
    { name: "is_active", label: "Active", type: "boolean" },
  ],
  defaults: {
    title: "",
    body: "",
    type: "info",
    target_audience: "all",
    starts_at: "",
    ends_at: "",
    is_active: true,
  },
})

export const ChangelogPage = createResourcePage({
  title: "Changelog",
  hooks: useChangelog,
  columns: changelogColumns,
  schema: changelogSchema,
  fields: [
    { name: "version", label: "Version", type: "text" },
    { name: "title", label: "Title", type: "text" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "type", label: "Type", type: "enum", values: CHANGELOG_TYPES },
    { name: "published_at", label: "Published at", type: "datetime-local" },
    { name: "is_published", label: "Published", type: "boolean" },
  ],
  defaults: {
    version: "",
    title: "",
    description: "",
    type: "feature",
    published_at: "",
    is_published: false,
  },
})

export const HealthChecksPage = createResourcePage({
  title: "Health Checks",
  hooks: useHealthChecks,
  columns: healthCheckColumns,
  schema: healthCheckSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "check_type", label: "Check type", type: "enum", values: HEALTH_CHECK_TYPES },
    { name: "status", label: "Status", type: "enum", values: HEALTH_CHECK_STATUSES },
    { name: "response_time_ms", label: "Response time (ms)", type: "number" },
    { name: "message", label: "Message", type: "textarea" },
    { name: "checked_at", label: "Checked at", type: "datetime-local" },
  ],
  defaults: {
    tenant_id: "",
    check_type: "db_connectivity",
    status: "healthy",
    response_time_ms: 0,
    message: "",
    checked_at: "",
  },
})

export const MetricsPage = createResourcePage({
  title: "Metrics",
  hooks: useMetrics,
  columns: metricColumns,
  schema: metricSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "metric_date", label: "Date", type: "date" },
    { name: "total_orders", label: "Orders", type: "number" },
    { name: "total_revenue", label: "Revenue", type: "text" },
    { name: "total_products", label: "Products", type: "number" },
    { name: "total_customers", label: "Customers", type: "number" },
    { name: "storage_used_mb", label: "Storage (MB)", type: "number" },
    { name: "bandwidth_used_mb", label: "Bandwidth (MB)", type: "number" },
    { name: "api_calls", label: "API calls", type: "number" },
  ],
  defaults: {
    tenant_id: "",
    metric_date: "",
    total_orders: 0,
    total_revenue: "0",
    total_products: 0,
    total_customers: 0,
    storage_used_mb: 0,
    bandwidth_used_mb: 0,
    api_calls: 0,
  },
})

export const UsageRecordsPage = createResourcePage({
  title: "Usage Records",
  hooks: useUsageRecords,
  columns: usageRecordColumns,
  schema: usageRecordSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "subscription_id", label: "Subscription ID", type: "text" },
    { name: "metric", label: "Metric", type: "enum", values: USAGE_METRICS },
    { name: "quantity", label: "Quantity", type: "text" },
    { name: "recorded_at", label: "Recorded at", type: "datetime-local" },
  ],
  defaults: {
    tenant_id: "",
    subscription_id: "",
    metric: "api_calls",
    quantity: "0",
    recorded_at: "",
  },
})

export const PaymentMethodsPage = createResourcePage({
  title: "Payment Methods",
  hooks: usePaymentMethods,
  columns: paymentMethodColumns,
  schema: paymentMethodSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "provider", label: "Provider", type: "enum", values: PAYMENT_PROVIDERS },
    { name: "provider_method_id", label: "Provider method ID", type: "text" },
    { name: "type", label: "Type", type: "enum", values: PAYMENT_METHOD_KINDS },
    { name: "last4", label: "Last 4", type: "text" },
    { name: "brand", label: "Brand", type: "text" },
    { name: "exp_month", label: "Exp month", type: "number" },
    { name: "exp_year", label: "Exp year", type: "number" },
    { name: "is_default", label: "Default", type: "boolean" },
  ],
  defaults: {
    tenant_id: "",
    provider: "stripe",
    provider_method_id: "",
    type: "card",
    last4: "",
    brand: "",
    exp_month: null,
    exp_year: null,
    is_default: false,
  },
})

export const InvoiceItemsPage = createResourcePage({
  title: "Invoice Items",
  hooks: useInvoiceItems,
  columns: invoiceItemColumns,
  schema: invoiceItemSchema,
  fields: [
    { name: "invoice_id", label: "Invoice ID", type: "text" },
    { name: "description", label: "Description", type: "text" },
    { name: "quantity", label: "Quantity", type: "number" },
    { name: "unit_amount", label: "Unit amount (cents)", type: "number" },
    { name: "amount", label: "Amount (cents)", type: "number" },
    { name: "plan_id", label: "Plan ID", type: "text" },
    { name: "period_start", label: "Period start", type: "date" },
    { name: "period_end", label: "Period end", type: "date" },
  ],
  defaults: {
    invoice_id: "",
    description: "",
    quantity: 1,
    unit_amount: 0,
    amount: 0,
    plan_id: "",
    period_start: "",
    period_end: "",
  },
})

export const PlanFeaturesPage = createResourcePage({
  title: "Plan Features",
  hooks: usePlanFeatures,
  columns: planFeatureColumns,
  schema: planFeatureSchema,
  fields: [
    { name: "plan_id", label: "Plan ID", type: "text" },
    { name: "feature_key", label: "Feature key", type: "text" },
    { name: "feature_value", label: "Feature value", type: "text" },
    { name: "feature_type", label: "Type", type: "enum", values: FEATURE_TYPES },
  ],
  defaults: {
    plan_id: "",
    feature_key: "",
    feature_value: "",
    feature_type: "boolean",
  },
})

export const SubscriptionItemsPage = createResourcePage({
  title: "Subscription Items",
  hooks: useSubscriptionItems,
  columns: subscriptionItemColumns,
  schema: subscriptionItemSchema,
  fields: [
    { name: "subscription_id", label: "Subscription ID", type: "text" },
    { name: "plan_id", label: "Plan ID", type: "text" },
    { name: "quantity", label: "Quantity", type: "number" },
    { name: "unit_price", label: "Unit price (cents)", type: "number" },
    { name: "total_price", label: "Total price (cents)", type: "number" },
  ],
  defaults: {
    subscription_id: "",
    plan_id: "",
    quantity: 1,
    unit_price: 0,
    total_price: 0,
  },
})

export const SubscriptionEventsPage = createResourcePage({
  title: "Subscription Events",
  hooks: useSubscriptionEvents,
  columns: subscriptionEventColumns,
  schema: subscriptionEventSchema,
  fields: [
    { name: "subscription_id", label: "Subscription ID", type: "text" },
    { name: "event_type", label: "Event", type: "enum", values: SUBSCRIPTION_EVENT_TYPES },
    { name: "from_plan_id", label: "From plan", type: "text" },
    { name: "to_plan_id", label: "To plan", type: "text" },
    { name: "triggered_by", label: "Triggered by", type: "enum", values: EVENT_TRIGGERED_BY },
  ],
  defaults: {
    subscription_id: "",
    event_type: "created",
    from_plan_id: "",
    to_plan_id: "",
    triggered_by: "admin",
  },
})

export const TenantConfigsPage = createResourcePage({
  title: "Tenant Configurations",
  hooks: useTenantConfigs,
  columns: tenantConfigColumns,
  schema: tenantConfigSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "key", label: "Key", type: "text" },
    { name: "value", label: "Value", type: "textarea" },
    { name: "encrypted", label: "Encrypted", type: "boolean" },
  ],
  defaults: { tenant_id: "", key: "", value: "", encrypted: false },
})

export const SupportMessagesPage = createResourcePage({
  title: "Support Messages",
  hooks: useSupportMessages,
  columns: supportMessageColumns,
  schema: supportMessageSchema,
  fields: [
    { name: "ticket_id", label: "Ticket ID", type: "number" },
    { name: "sender_type", label: "Sender type", type: "enum", values: MESSAGE_SENDER_TYPES },
    { name: "sender_id", label: "Sender ID", type: "number" },
    { name: "body", label: "Message", type: "textarea" },
    { name: "is_internal", label: "Internal note", type: "boolean" },
  ],
  defaults: {
    ticket_id: 0,
    sender_type: "admin",
    sender_id: null,
    body: "",
    is_internal: false,
  },
})

export const ImpersonationTokensPage = createResourcePage({
  title: "Impersonation Tokens",
  hooks: useImpersonationTokens,
  columns: impersonationTokenColumns,
  schema: impersonationTokenSchema,
  fields: [
    { name: "tenant_id", label: "Tenant ID", type: "text" },
    { name: "admin_id", label: "Admin user ID", type: "number" },
    { name: "expires_at", label: "Expires at", type: "datetime-local" },
  ],
  defaults: { tenant_id: "", admin_id: 0, expires_at: "" },
})
